#服务端设置
server:
  port: 8080
  #ip,域名都设置在address
  address: localhost
  session:
    timeout: 30
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8

#HTTP编码设置
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

#数据库设置（如何解决MySQL在高版本需要指明是否进行SSL连接问题：useSSL=true）【详情见mybatis笔记--关于MySql链接url参数的设置】
#mysql 连接url中useUnicode=true&characterEncoding=UTF-8 的作用
#1. 存数据时：
#    数据库在存放项目数据的时候会先用UTF-8格式将数据解码成字节码，然后再将解码后的字节码重新使用GBK编码存放到数据库中。
#2.取数据时：
#    在从数据库中取数据的时候，数据库会先将数据库中的数据按GBK格式解码成字节码，然后再将解码后的字节码重新按UTF-8格式编码数据，最后再将数据返回给客户端。
#8八小时失效问题autoReconnect
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/lishaoxiong?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
      username: lishaoxiong
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver

#日志设置
logging:
# 日志文件,绝对路径或相对路径（可以设置文件名称）
  file: D:\RedisTest\src\main\log\log.log
  # 保存日志文件目录路径（文件名称：spring.log）
  #path: E:\Users\83990\eclipse-workspace\SpringbootWeb\SpringbootWeb\src\main\webapp\logfiles
  level:
    com:
      favorites: DEBUG
    org:
      springframework:
        web: INFO
      hibernate: ERROR